@echo off
get_input_data test-data.txt [3-b3-01] | test.exe >  3-b3-testresult.txt
get_input_data test-data.txt [3-b3-02] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-03] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-04] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-05] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-06] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-07] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-08] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-09] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-10] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-11] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-12] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-13] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-14] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-15] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-16] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-17] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-18] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-19] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-20] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-21] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-22] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-23] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-24] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-25] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-26] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-27] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-28] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-29] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-30] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-31] | test.exe >> 3-b3-testresult.txt
get_input_data test-data.txt [3-b3-32] | test.exe >> 3-b3-testresult.txt
